/*
 * Signed Cloud
 * Copyright (C) 2026 Wultra s.r.o.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.wultra.signercloud.server.sca;


import com.wultra.signercloud.server.document.DocumentContent;
import lombok.Builder;
import lombok.Getter;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Version;
import org.springframework.data.jdbc.core.mapping.AggregateReference;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.Instant;

/**
 * TODO
 *
 * @author Michal Rozehnal, michal.rozehnal@wultra.com
 */
@Table("signing_transaction")
@Getter
@Builder(toBuilder = true)
public class SigningTransactionEntity {

    @Id
    @Column("id")
    private String id;

    /*
     * This also tells Spring Data JDBC that an entity with a null
     * version is new, even though its UUID ID is already assigned.
     */
    @Version
    @Column("version")
    private Long version;

    @Column("external_id")
    private String externalId;

    @Column("document_name")
    private String documentName;

    @Column("file_name")
    private String fileName;

    @Column("file_size")
    private long fileSize;

    @Column("document_content_id")
    private AggregateReference<DocumentContent, Long> documentContent;

    @Column("signed_document_content_id")
    private AggregateReference<DocumentContent, Long> signedDocumentContent;

    @Column("certificate_base64")
    private String certificateBase64;

    /*
     * JSON array of Base64-encoded certificates.
     * The end-entity certificate is stored separately.
     */
    @Column("certificate_chain_json")
    private String certificateChainJson;

    /*
     * Hash generated by DocumentSigningService.computeToBeSigned(...).
     */
    @Column("to_be_signed_hash_base64")
    private String toBeSignedHashBase64;

    /*
     * Reuse this exact value when creating the final signed PDF.
     */
    @Column("signature_date")
    private Instant signatureDate;

    @Column("visual_signature_json")
    private String visualSignatureJson;

    @Column("authorization_expires_at")
    private Instant authorizationExpiresAt;

    @Column("status")
    private SigningTransactionStatus status;

    @Column("created_at")
    private Instant createdAt;

    @Column("updated_at")
    private Instant updatedAt;

    @Column("completed_at")
    private Instant completedAt;
}
