@startuml
hide stereotypes
hide circle

class sc_signer {
    ID bigint PK
    timestamp_created timestamp(6) NN
    timestamp_last_updated timestamp(6)
    signer_external_id varchar(255) U NN
    user_id varchar(255) NN
    csr CLOB NN
    certificate CLOB
    timestamp_certificate_expiration timestamp(6)
    signer_status varchar(50) NN (ACTIVE/BLOCKED/REMOVED/REVOKED)
}

class sc_document {
    ID bigint PK
    timestamp_created timestamp(6) NN
    timestamp_last_updated timestamp(6)
    document_id varchar(255) U NN
    signer_id bigint FK
    external_id varchar(255)
    document_name varchar(255) NN
    file_name varchar(255) NN
    file_size integer NN
    document_content_id bigint FK
    hash varchar(255) NN
    document_status varchar(50) NN (WAITING/REJECTED/SIGNED)
    signature varchar(255)
}

class sc_document_content {
    ID bigint PK
    content BLOB NN
}

sc_document "sc_document_signer_id_fk" --> sc_signer
sc_document "sc_document_document_content_id_fk" --> sc_document_content

sc_signer_seq -> sc_signer
sc_document_seq -> sc_document
sc_document_content_seq -> sc_document_content

note as note1
Legend:
PK = Primary Key
FK = Foreign Key
NN = Not Null
U = Unique
end note

@enduml