@startuml
hide empty description

[*] --> ACTIVE
ACTIVE --> BLOCKED
ACTIVE --> REVOKED
ACTIVE --> REMOVED
ACTIVE --> EXPIRED

BLOCKED --> ACTIVE
BLOCKED --> REVOKED
BLOCKED --> REMOVED

REVOKED --> [*]
REMOVED --> [*]
EXPIRED --> [*]

@enduml