spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/signer_cloud_server}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.pool-name=HikariPool-Signer-Cloud-Server

spring.sql.init.mode=never
spring.data.jdbc.repositories.enabled=true

spring.application.name=signer-cloud-server

banner.application.name=${spring.application.name}
banner.application.version=@project.version@

signer-cloud.server.powerauth.url=${POWERAUTH_URL:http://localhost:8080/powerauth-java-server/rest}
signer-cloud.server.powerauth.rest-client-configuration.power-auth-client-token=${POWERAUTH_CLIENT_TOKEN:}
signer-cloud.server.powerauth.rest-client-configuration.power-auth-client-secret=${POWERAUTH_CLIENT_SECRET:}

signer-cloud.server.ejbca.certificate-profile-name=UserCertificateProfile
signer-cloud.server.ejbca.end-entity-profile-name=UserEndEntityProfile
signer-cloud.server.ejbca.certificate-authority-name=IssuingCA
signer-cloud.server.ejbca.rest-client-configuration.base-url=${EJBCA_URL:}
signer-cloud.server.ejbca.rest-client-configuration.certificate-auth-enabled=true
signer-cloud.server.ejbca.rest-client-configuration.use-custom-keystore=true
signer-cloud.server.ejbca.rest-client-configuration.key-store-password=${EJBCA_KEYSTORE_PASSWORD:}
signer-cloud.server.ejbca.rest-client-configuration.key-alias=${EJBCA_KEY_ALIAS:}
signer-cloud.server.ejbca.rest-client-configuration.key-password=${EJBCA_KEY_PASSWORD:}
signer-cloud.server.ejbca.rest-client-configuration.key-store-bytes=${EJBCA_KEYSTORE_BASE64:}

signer-cloud.server.security.auth.type=OAUTH2

# OAuth 2.0
spring.security.oauth2.resource-server.jwt.issuer-uri=${OAUTH2_ISSUER_URI:}
spring.security.oauth2.resource-server.jwt.audiences=${OAUTH2_AUDIENCES:}

signer-cloud.server.document.cleanup.cron=2 1 0 * * *
signer-cloud.server.document.waiting.retention-period=
signer-cloud.server.document.waiting.timeout=3600s
signer-cloud.server.document.rejected.retention-period=
signer-cloud.server.document.signed.retention-period=

signer-cloud.server.document.content-hash-algorithm=SHA256
signer-cloud.server.document.signature-hash-algorithm=SHA384

signer-cloud.server.signer.expiration.job.cron=3 2 0 * * *
signer-cloud.server.signer.expiration.job.limit=1000
signer-cloud.server.signer.expiration.callback-enabled=true

signer-cloud.server.callback.dispatch-pending-callback-events.job.cron=0 1 * * * *
signer-cloud.server.callback.dispatch-pending-callback-events.job.limit=100
signer-cloud.server.callback.cleanup-callback-events.job.cron=0 11 * * * *
signer-cloud.server.callback.cleanup-callback-events.job.limit=1000
signer-cloud.server.callback.rerun-stale-callback-events.job.cron=0 23 * * * *
signer-cloud.server.callback.rerun-stale-callback-events.job.limit=1000

# TODO (racansky, 2025-08-13) remove metrics; temporary solution, propagated to OTEL but so far we may observe via endpoint
management.endpoints.web.exposure.include=health,info,metrics
management.info.git.mode=simple

management.tracing.sampling.probability=1.0

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=51MB

server.forward-headers-strategy=framework