spring.datasource.url=jdbc:postgresql://localhost:5432/signer_cloud_server
spring.datasource.username=signer_cloud_server

server.port=8090

signer-cloud.server.ejbca.certificate-profile-name=UserCertificateProfile
signer-cloud.server.ejbca.end-entity-profile-name=UserEndEntityProfile
signer-cloud.server.ejbca.certificate-authority-name=IssuingCA
signer-cloud.server.pades.tsa-url=https://freetsa.org/tsr
signer-cloud.server.pades.signature-level=PADES_B_T

signer-cloud.server.callback.expired.url=https://example.com/callback/expired
signer-cloud.server.callback.renewed.url=https://example.com/callback/renewed

signer-cloud.server.security.auth.type=BASIC_HTTP
spring.security.user.name=user
spring.security.user.password=dummypassword

signer-cloud.server.document.cleanup.cron=0 0/1 * * * *

signer-cloud.server.signer.expiration.job.cron=0 0/1 * * * *

logging.level.com.wultra=DEBUG
logging.level.io.getlime=DEBUG
#logging.level.org.springframework.jdbc.core=DEBUG

management.endpoints.web.exposure.include=*




signer-cloud.server.sca.qtsp-base-url=http://localhost:8088
signer-cloud.server.sca.sca-base-url=http://localhost:8090
signer-cloud.server.sca.ui-redirect-url=https://httpbingo.org/anything
