signer-cloud.server.ejbca.certificate-profile-name=Client
signer-cloud.server.ejbca.end-entity-profile-name=User
signer-cloud.server.ejbca.certificate-authority-name=IssuerCA
signer-cloud.server.ejbca.rest-client-configuration.base-url=https://smoke-ejbca-dev.wultra.app/ejbca/ejbca-rest-api
signer-cloud.server.ejbca.rest-client-configuration.certificate-auth-enabled=true
signer-cloud.server.ejbca.rest-client-configuration.key-store-password=TODO
signer-cloud.server.ejbca.rest-client-configuration.key-alias=TODO
signer-cloud.server.ejbca.rest-client-configuration.key-password=TODO
signer-cloud.server.ejbca.rest-client-configuration.key-store-bytes=TODO
