signer-cloud.server.ejbca.certificate-profile-name=Client
signer-cloud.server.ejbca.end-entity-profile-name=User
signer-cloud.server.ejbca.certificate-authority-name=IssuerCA
signer-cloud.server.ejbca.rest-client-configuration.base-url=http://localhost:8080/ejbca/ejbca-rest-api
#signer-cloud.server.ejbca.rest-client-configuration.certificate-auth-enabled=true TODO (racansky, 2025-08-01) configure security
